version: "3.8"
services:
  weather_service:
    build: weather_service
    ports:
      - "7000:8080"
    environment:
      - CLIENT_URL=https://weatherapi-com.p.rapidapi.com/current.json?q=Minsk
      - CLIENT_KEY=6fe40fb762mshd754f02393d488ep134ff5jsn16f584ba1545
      - CLIENT_HOST=weatherapi-com.p.rapidapi.com
      - POSTGRES_PASSWORD=root
      - POSTGRES_USERNAME=postgres
      - POSTGRES_URL=jdbc:postgresql://weather-db:5432/weather_data
      - TIME_BETWEEN_REQUESTS=100000
    depends_on:
      - weather-db
    restart: always
  weather-db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather_data
    volumes:
      - weather-db:/var/lib/postgresql/data
    restart: always
volumes:
  weather-db: